name: Build and Deploy

on:
  push:
    tags:
      - "*.*.*"


permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version-file: 'go.mod'

      - name: Read version
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Compile binary
        run: >-
          env CGO_ENABLED=0 
          go build -trimpath -ldflags="-s -w" -o "bin/spine-${VERSION}.bin" .

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ env.VERSION }}
          files: bin/spine-*.bin
          make_latest: true
          fail_on_unmatched_files: true
