name: Build and Deploy

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: spine-${{ github.ref_name }}.bin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version-file: 'go.mod'

      - name: Compile binary
        run: >-
          env CGO_ENABLED=0 
          go build -trimpath -ldflags="-s -w -X main.version=${{ github.ref_name }}" 
          -o "${{ env.BINARY_NAME }}" .

      - name: Write checksum
        run: |
          sha256sum ${{ env.BINARY_NAME }} > ${{ env.BINARY_NAME }}.checksum

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ github.ref_name }}
          files: |
            ${{ env.BINARY_NAME }}
            ${{ env.BINARY_NAME }}.checksum
          make_latest: true
          fail_on_unmatched_files: true
