name: Build and Deploy

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  RELEASE: ${{ github.run_number }}

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version-file: 'go.mod'

      - name: Read version
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Compile binary
        run: >-
          env CGO_ENABLED=0 
          go build -trimpath -ldflags="-s -w" -o "bin/spine-${VERSION}-${RELEASE}".bin .

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/release/')
        with:
          make_latest: true
          name: "${VERSION}-${RELEASE}"
          files: |
            bin/spine-${VERSION}-${RELEASE}.bin
